name: Daily Earthquake Data Fetch

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Fetch latest USGS earthquakes (last 30 days)
        run: |
          python scripts/fetch_data.py --output data/earthquakes_last30.csv

      - name: Process earthquake data
        run: |
          python scripts/process_data.py --input data/earthquakes_last30.csv --output data/stats_last30.csv

      - name: Commit and push updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): update earthquake data (daily)"
          file_pattern: data/earthquakes_last30.csv data/stats_last30.csv
